// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKrR_IzWcbeepBp-ssQcXIie5ujb4xUBs',
    appId: '1:395474356966:web:3b6794f49c90876e95c927',
    messagingSenderId: '395474356966',
    projectId: 'e-commerace-app2',
    authDomain: 'e-commerace-app2.firebaseapp.com',
    storageBucket: 'e-commerace-app2.firebasestorage.app',
    measurementId: 'G-XPN538ECFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuqJRv3Tm1e-kmFcX6TLY_PzXLvLi08UU',
    appId: '1:395474356966:android:96942dd8eab39e2895c927',
    messagingSenderId: '395474356966',
    projectId: 'e-commerace-app2',
    storageBucket: 'e-commerace-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATLfRo47IwlzQDv4TlOi0evG_tcvUZHJk',
    appId: '1:395474356966:ios:108d464ce23a1b5f95c927',
    messagingSenderId: '395474356966',
    projectId: 'e-commerace-app2',
    storageBucket: 'e-commerace-app2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATLfRo47IwlzQDv4TlOi0evG_tcvUZHJk',
    appId: '1:395474356966:ios:108d464ce23a1b5f95c927',
    messagingSenderId: '395474356966',
    projectId: 'e-commerace-app2',
    storageBucket: 'e-commerace-app2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKrR_IzWcbeepBp-ssQcXIie5ujb4xUBs',
    appId: '1:395474356966:web:085e1d21418fb44e95c927',
    messagingSenderId: '395474356966',
    projectId: 'e-commerace-app2',
    authDomain: 'e-commerace-app2.firebaseapp.com',
    storageBucket: 'e-commerace-app2.firebasestorage.app',
    measurementId: 'G-MYJ94E3FW9',
  );

}